image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-requests-microservice:
  stage: build
  script:
    gradle requests-microservice:assemble requests-microservice:testClasses

checkStyle-requests-microservice:
  stage: staticAnalysis
  script:
    gradle requests-microservice:checkstyleMain requests-microservice:checkStyleTest
  allow_failure: true


PMD-requests-microservice:
  stage: staticAnalysis
  script:
    gradle requests-microservice:pmdMain
  allow_failure: true

test-requests-microservice:
  stage: test
  script:
    - gradle requests-microservice:test requests-microservice:jacocoTestReport
    - cat requests-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
